databases:
  - name: postgres_45uf
    databaseName: postgres_45uf
    user: postgres_45uf_user
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: rails exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_45uf
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction